# Generated by Django 3.2 on 2022-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0002_opt_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opt',
            name='content',
            field=models.CharField(max_length=225),
        ),
    ]
