# Generated by Django 3.2 on 2022-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0003_alter_opt_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='opt',
            name='image',
            field=models.CharField(default='g', max_length=225, null=True),
        ),
    ]
