# Generated by Django 3.2 on 2022-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0005_alter_opt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='title',
            field=models.CharField(default='ss', max_length=225),
        ),
    ]
