# Generated by Django 3.2 on 2022-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0006_goods_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
