# Generated by Django 3.2 on 2022-04-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0009_alter_goods_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.genre'),
        ),
    ]
