# Generated by Django 3.2 on 2022-04-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0010_goods_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.genre'),
        ),
    ]
