# Generated by Django 3.2 on 2022-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0011_alter_goods_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='choice_image',
            field=models.TextField(default='ss', verbose_name='选择展示图片'),
        ),
    ]
