# Generated by Django 3.2 on 2022-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0012_goods_choice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='choice_image',
        ),
    ]
