# Generated by Django 3.2 on 2022-02-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('account', models.CharField(max_length=11, verbose_name='账户')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('mailbox', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
    ]
