# Generated by Django 3.2 on 2022-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_receivinginformation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivinginformation',
            name='username',
            field=models.CharField(max_length=5, verbose_name='收件人姓名'),
        ),
    ]
