# Generated by Django 3.2 on 2022-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_alter_receivinginformation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='判断是否注册成功'),
        ),
    ]
