# Generated by Django 3.2 on 2022-04-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='receiving',
            field=models.ForeignKey(db_column='receive_id', on_delete=django.db.models.deletion.CASCADE, to='user.receiving'),
        ),
    ]
