# Generated by Django 3.2 on 2022-04-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_shoppingcart_receiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.IntegerField(choices=[(0, '删除'), (1, '购物车'), (2, '待付款'), (3, '待发货'), (4, '取消订单'), (5, '已签收'), (6, '待收货')], db_column='status', default=2, verbose_name='当前购物车商品的存在状态'),
        ),
    ]
