# Generated by Django 3.2 on 2022-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_shoppingcart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='type_one',
        ),
        migrations.RemoveField(
            model_name='price',
            name='type_three',
        ),
        migrations.RemoveField(
            model_name='price',
            name='type_two',
        ),
        migrations.AddField(
            model_name='price',
            name='five',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='four',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='one',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='six',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='three',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='two',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
